name: Deploy Laravel + Vue SPA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker build -t laravel-vue-app .

      - name: Deploy to server via ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          port: 8080
          script: |
            cd /var/www/html/laravel-vue-spa
            git pull origin main
            docker-compose down
            docker-compose up -d --build
